#!/usr/bin/env bash
#File: range

function work {
  local ar=()
  local i=0
  if [[ $1 -ge 0 ]]
  then
    while [[ $i -lt $1 ]]
    do
      ar+=($i)
      let i=$i+1
    done
  else
    while [[ $i -gt $1 ]]
    do
      ar+=($i)
      let i=$i-1
    done
  fi
  echo "${ar[*]}"
}

work $1
